[build]
  functions = "functions"
  command = "npm run build"  # Puedes ajustar esto según tu configuración

[[plugins]]
  path = "send-email.js"
  package = "netlify-plugin-functions-install"

[[headers]]
  Access-Control-Allow-Origin = ["*"]
  Access-Control-Allow-Methods = ["GET", "POST", "PUT", "DELETE"]
  Access-Control-Allow-Headers = ["Content-Type"]
